name: fluxestore
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  assets: ^0.0.1
  flutter_rating_bar: ^4.0.1
  meta: ^1.9.1
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.8
  bloc: ^8.1.2
  flutter_bloc: ^8.1.4
  csc_picker: ^0.2.7
  carousel_slider: ^4.2.1
  lottie: ^2.7.0
  http:
  intl: ^0.17.0
  sliding_switch: ^1.1.0
  carousel_indicator: ^1.0.6
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  toastification: ^1.2.1
  url_launcher: ^6.2.5
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_toggle_tab: ^1.4.1
  google_fonts: ^6.1.0
  toggle_switch: ^2.1.0
  expandable: ^5.0.1
  customizable_counter: ^1.0.4
  step_progress_indicator: ^1.0.2
  dropdown_textfield: ^1.0.8
  
  

  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_fade.png"
  min_sdk_android: 21
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - .env

  fonts:
    - family:  PrimaryIcons
      fonts:
        - asset: assets/fonts/PrimaryIcons.ttf
          weight: 700
    - family:  SecondaryIcons
      fonts:
        - asset: assets/fonts/SecondaryIcons.ttf
          weight: 700        
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product_Sans_Bold.ttf
          weight: 700
        - asset: assets/fonts/Product_Sans_Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans_Light.ttf
          weight: 100
    - family:  NewIcon
      fonts:
        - asset: assets/fonts/NewIcon.ttf
          weight: 700

