/// Flutter icons NewIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NewIcon
///      fonts:
///       - asset: fonts/NewIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NewIcon {
  NewIcon._();

  static const _kFontFam = 'NewIcon';
  static const String? _kFontPkg = null;

  static const IconData filterBig = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
