name: kuldeep_s_application10
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  google_sign_in: ^5.0.7
  smooth_page_indicator: ^1.1.0
  google_maps_flutter: ^2.5.0
  grouped_list: ^5.1.2
  flutter_svg_provider: ^1.0.6
  flutter_svg: ^2.0.10+1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Acme
      fonts: 
        - asset: assets/fonts/AcmeRegular.ttf
          weight: 400
    - family: Work Sans
      fonts: 
        - asset: assets/fonts/WorkSansRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/WorkSansRomanRegular.ttf
          weight: 400
